### PR TITLE
cuprated: Bad reorg recover

### LINKED ISSUE #405: Proposal: the log level for adding new blocks should be `INFO` instead of `DEBUG`
Right now when the node is launched, it's not really clear whether it's functioning. Changing `stdout = { level = "info" }` to `debug` yields too much output to `STDOUT`.

```
cuprate@xmr-cuprate:~$ ./cuprated
Using config at: /home/cuprate/Cuprated.toml
2025-03-13T18:11:03.091200Z  INFO init_hardfork_state{chain_height=3367024}: Initializing hard-fork state this may take a while.
2025-03-13T18:11:03.091208Z  INFO init_weight_cache{chain_height=3367024 chain=Main}: Initializing weight cache this may take a while.
2025-03-13T18:11:03.091358Z  INFO init_weight_cache{chain_height=3367024 chain=Main}:get_long_term_weights{range=3267024..3367024 chain=Main}: getting block long term weights.
2025-03-13T18:11:03.091216Z  INFO init_difficulty_cache{chain_height=3367024 chain=Main}: Initializing difficulty cache this may take a while.
2025-03-13T18:11:03.095474Z  INFO init_difficulty_cache{chain_height=3367024 chain=Main}:get_blocks_timestamps{block_heights=3366289..3367024 chain=Main}: Getting blocks timestamps
2025-03-13T18:11:03.157383Z  INFO init_difficulty_cache{chain_height=3367024 chain=Main}: Current chain height: 3367024, accounting for 735 blocks timestamps
2025-03-13T18:11:03.157461Z  INFO init_hardfork_state{chain_height=3367024}: Initialized Hfs, current fork: V16, HFVotes { total: 10080, V1: 10080, V2: 10080, V3: 10080, V4: 10080, V5: 10080, V6: 10080, V7: 10080, V8: 10080, V9: 10080, V10: 10080, V11: 10080, V12: 10080, V13: 10080, V14: 10080, V15: 10080, V16: 10080 }
2025-03-13T18:11:03.157745Z  INFO init_weight_cache{chain_height=3367024 chain=Main}:get_block_weights{range=3366924..3367024 chain=Main}: getting block weights.
2025-03-13T18:11:03.163558Z  INFO init_weight_cache{chain_height=3367024 chain=Main}: Initialized block weight cache, chain-height: 3367024, long term weights length: 100000, short term weights length: 100
2025-03-13T18:11:03.525224Z  INFO Loading peers from file: /home/cuprate/.cache/cuprate/addressbook/ClearNet
2025-03-13T18:11:03.527389Z  INFO Starting outbound connection maintainer, target outbound connections: 64
2025-03-13T18:11:03.527429Z  INFO inbound_server: Starting inbound connection server
2025-03-13T18:11:03.528336Z  INFO Starting blockchain syncer
(end)
```

While we can see the new blocks in the log `grep`ped by `block`:

```
...
2025-03-13T18:23:36.925610Z DEBUG got blockchain context: BlockchainContext { cumulative_difficulty: 432913247583951277, context_to_verify_block: ContextToVerifyBlock { median_wei>
2025-03-13T18:23:36.925663Z DEBUG Preparing block for verification, expected height: 3367031
2025-03-13T18:23:36.943678Z DEBUG verifying block: a5febb73a4f5adf47c0b741f23d3abf4717704b09cc574725fcde26c0a524725
2025-03-13T18:23:36.944219Z DEBUG Verifying block header.
2025-03-13T18:23:36.944271Z DEBUG Updating blockchain cache with new block, height: 3367031
2025-03-13T18:23:36.944292Z DEBUG Accounting for new blocks timestamp (1741890214) and cumulative_difficulty (432913761077076268)
2025-03-13T18:23:36.944311Z DEBUG Adding new block's 3367031 weights to block cache, weight: 130317, long term weight: 176470
2025-03-13T18:23:36.944408Z DEBUG Accounting for new blocks vote, height: 3367031, vote: V16
2025-03-13T18:23:36.950959Z DEBUG queuing block at chain height 3367032 for broadcast
...
```

### LINKED ISSUE #421: `cuprated` does not log block batches after initial sync
## Environment
All, `cuprated v0.0.1`.

## Bug
`cuprated` does not log when a block batch has been added after the initial `Synchronised with the network.` message.

## Expected behavior
All block batches to be logged.

## Steps to reproduce
1. Sync `cuprated` until `Synchronised with the network.` message appears
2. Wait
3. `status`, see height past initial sync height
4. See no sync messages

## Log
```
2025-03-23T06:06:36.414055Z  INFO incoming_block_batch{start_height=3374075 len=3}: Successfully added block batch fast_sync=false
2025-03-23T06:06:36.568945Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-23T06:06:37.073961Z  INFO incoming_block_batch{start_height=3374078 len=1}: Successfully added block batch fast_sync=false
2025-03-23T06:06:37.793049Z  INFO incoming_block_batch{start_height=3374079 len=1}: Successfully added block batch fast_sync=false
2025-03-23T06:06:37.793070Z  INFO Synchronised with the network.
status
STATUS:
  uptime: 22h 17m 27s,
  height: 3375193,
  top_hash: b54b627129b04a541e915b06fe45bdb374020aad4dfac77ac6d9332a86ec2b99
```

### PR DESCRIPTION
**Pull request by Boog900**
closes #421 
closes #405

### What
Adds recovery for failed reorgs

### CODE REVIEW

File: binaries/cuprated/src/blockchain/manager/handler.rs [hunk 1]
```diff
@@ -394,14 +427,106 @@ impl super::BlockchainManager {
...
+    ///
+    /// This function takes the old chain's [`ChainId`] and reverts the chain state to back to before
+    /// the reorg was attempted.
+    ///
+    /// # Panics
+    ///
+    /// This function will panic if any internal service returns an unexpected error that we cannot
+    /// recover from.
+    #[instrument(name = "reverse_reorg", skip_all, level = "info")]
+    async fn reverse_reorg(&mut self, old_main_chain_id: ChainId) {
```
Comment (Boog900) [inline binaries/cuprated/src/blockchain/manager/handler.rs:467]: the new function to reverse a reorg

File: binaries/cuprated/src/blockchain/manager/handler.rs [hunk 2]
```diff
@@ -115,6 +138,15 @@ impl super::BlockchainManager {
...
         self.broadcast_block(block_blob, chain_height).await;
 
+        info!(
+            hash = hex::encode(
+                self.blockchain_context_service
+                    .blockchain_context()
+                    .top_hash
+            ),
+            "Successfully added block"
+        );
```
Comment (Boog900) [inline binaries/cuprated/src/blockchain/manager/handler.rs:148]: added some more logs - now on every new tx

File: storage/blockchain/src/ops/alt_block/chain.rs [hunk 3]
```diff
@@ -42,7 +42,6 @@ pub fn update_alt_chain_info(
                 info.parent_chain = parent_chain.into();
             }
 
-            info.chain_height = alt_block_height.height + 1;
```
Comment (Boog900) [inline storage/blockchain/src/ops/alt_block/chain.rs:45]: this line is incorrect - it's effect is luckily are non-critical it just prevents fully recovering a reorg, you could only recover 1 block. The rest would be re-downloaded.

File: binaries/cuprated/src/blockchain/manager/handler.rs [hunk 4]
```diff
@@ -568,7 +684,49 @@ impl super::BlockchainManager {
...
 }
+
+/// Creates a [`VerifiedBlockInformation`] from an alt-block known to be valid.
+///
+/// # Panics
+///
+/// This may panic if used on an invalid block.
+pub fn alt_block_to_verified_block_information(
+    block: AltBlockInformation,
+    blockchin_ctx: &BlockchainContext,
```
Comment (hinto-janai) [inline binaries/cuprated/src/blockchain/manager/handler.rs:701]:
```suggestion
    blockchain_ctx: &BlockchainContext,
```

**Comment by hinto-janai** [comment]
Looks good - I'm going to test this on tier 1s and wait for some reorgs.

**Comment by Boog900** [comment]
Sure although FWIW this doesn't effect normal reorgs, this only changes bad reorgs which will only happen when someone is purposefully doing something malicious.
