### PR TITLE
Cuprated: Fix reorgs

### LINKED ISSUE #404: Stuck on re-orgs
## Bug
Cuprate struggles to handle alt-blocks

## Log

```
2025-03-12T16:25:05.763628Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:25:05.783531Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:25:34.725632Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:25:43.922410Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:25:43.923871Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:26:01.172687Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:26:01.829728Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:26:01.830084Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:26:31.160953Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:26:32.338206Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:26:32.339295Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:27:01.128378Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:27:01.445344Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:27:01.446267Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:27:31.365338Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:27:32.015854Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:27:32.017144Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:28:01.230414Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:28:02.156343Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:28:02.157181Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:28:32.218018Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:28:32.706109Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:28:32.706931Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:29:01.234183Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:29:07.743187Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:29:07.744348Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:29:31.364990Z  INFO block_downloader: Attempting to download blocks from peers, this may take a while.
2025-03-12T16:29:31.867630Z  INFO incoming_block_batch{start_height=3366243 len=1}: Successfully added block batch alt_chain=true
2025-03-12T16:29:31.868741Z  INFO incoming_block_batch{start_height=3366244 len=1}: Successfully added block batch alt_chain=true
```

Here Cuprate is repeatedly downloading an alt chain (it is not adding it to the DB multiple times).

### PR DESCRIPTION
**Pull request by Boog900**
### What
Fixes #404

### CODE REVIEW

File: binaries/cuprated/src/blockchain/manager/handler.rs [hunk 1]
```diff
@@ -396,7 +396,7 @@ impl super::BlockchainManager {
             .await
             .expect(PANIC_CRITICAL_SERVICE_ERROR)
             .call(BlockchainWriteRequest::PopBlocks(
-                current_main_chain_height - split_height + 1,
+                current_main_chain_height - split_height,
```
Comment (Boog900) [inline binaries/cuprated/src/blockchain/manager/handler.rs:399]: fixes some off by ones .. again, due to chain height vs top height.

File: binaries/cuprated/src/blockchain/manager/tests.rs [hunk 2]
```diff
@@ -0,0 +1,204 @@
...
+            },
+            proofs: None,
+        },
+        transactions: vec![],
+    }
+}
+
+#[tokio::test]
+async fn simple_reorg() {
+    // create 2 managers
```
Comment (Boog900) [inline binaries/cuprated/src/blockchain/manager/tests.rs:98]: I have added a test to make sure reorgs work now.

File: consensus/context/src/alt_chains.rs [hunk 3]
```diff
@@ -52,9 +52,10 @@ impl AltChainContextCache {
         block_weight: usize,
         long_term_block_weight: usize,
         timestamp: u64,
+        cumulative_difficulty: u128,
     ) {
         if let Some(difficulty_cache) = &mut self.difficulty_cache {
-            difficulty_cache.new_block(height, timestamp, difficulty_cache.cumulative_difficulty());
+            difficulty_cache.new_block(height, timestamp, cumulative_difficulty);
```
Comment (Boog900) [inline consensus/context/src/alt_chains.rs:58]: We were also calculating difficulty wrong for alt chains

File: storage/blockchain/src/ops/blockchain.rs [hunk 4]
```diff
@@ -91,13 +91,21 @@ pub fn cumulative_generated_coins(
 pub fn find_split_point(
     block_ids: &[BlockHash],
     chronological_order: bool,
+    include_alt_blocks: bool,
     table_block_heights: &impl DatabaseRo<BlockHeights>,
+    table_alt_block_heights: &impl DatabaseRo<AltBlockHeights>,
```
Comment (Boog900) [inline storage/blockchain/src/ops/blockchain.rs:96]: finding the split point now allows looking at alt blocks, we need to do this so we don't repeatedly ask for alt blocks

Comment (hinto-janai) [reply storage/blockchain/src/ops/blockchain.rs:96]: nit: could be `Option<&impl DatabaseRo<AltBlockHeights>>` without the `include_alt_blocks: bool`.

File: consensus/context/src/difficulty.rs [hunk 5]
```diff
@@ -36,15 +36,27 @@ pub struct DifficultyCacheConfig {
...
+    pub fixed_difficulty: Option<u128>,
 }
 
 impl DifficultyCacheConfig {
     /// Create a new difficulty cache config.
     ///
     /// # Notes
     /// You probably do not need this, use [`DifficultyCacheConfig::main_net`] instead.
-    pub const fn new(window: usize, cut: usize, lag: usize) -> Self {
-        Self { window, cut, lag }
```
Comment (hinto-janai) [inline consensus/context/src/difficulty.rs:47]: nit: is this `fn` needed? all fields are `pub`.

**Review by hinto-janai — APPROVED** [review]

File: storage/blockchain/src/ops/blockchain.rs (hunk 4 above)
Comment (Boog900) [reply storage/blockchain/src/ops/blockchain.rs:96]: I tried to change this but Rust is unhappy as it doesn't know the type of `table_alt_block_heights`
