### PR TITLE
P2P: fix deadlock

### LINKED ISSUE #383: sync stuck
status
STATUS:
  uptime: 0h 6m 30s,
  height: 3344340,
  top_hash: b83c5cda44b3bdc58b68c79f297710641065c829a08e024f1d89b26c98c881df
status
STATUS:
  uptime: 0h 24m 39s,
  height: 3344342,
  top_hash: 75663eb8312cabc55916211147f83471458db98cb9f42c51f695e749dd20b53b
status
STATUS:
  uptime: 2h 59m 34s,
  height: 3344342,
  top_hash: 75663eb8312cabc55916211147f83471458db98cb9f42c51f695e749dd20b53b

### PR DESCRIPTION
**Pull request by Boog900**
### What

Fixes #383

### How
Added a timeout for handling request to Cuprate and also add a new `Client` type that doesn't require requests be handled one at a time but only supports certain messages

### CODE REVIEW

File: p2p/p2p-core/src/client/timeout_monitor.rs [hunk 1]
```diff
@@ -54,6 +54,14 @@ where
...
     loop {
+        tokio::select! {
+            () = peer_information.handle.closed() => {
+                tracing::debug!("Closing timeout monitor, connection disconnected.");
+                return Ok(());
+            }
+            _ = interval.tick() => ()
+        }
+
         interval.tick().await;
```
Comment (bonedaddy) [inline p2p/p2p-core/src/client/timeout_monitor.rs:65]: Pretty sure you would want to remove line 65 `interval.tick().await`.

The `tokio::select` statement already handles awaiting the interval. So this would another tick before processing the event loop.

Comment (Boog900) [reply p2p/p2p-core/src/client/timeout_monitor.rs:65]: yes, good spot!

**Review by SyntheticBird45 — APPROVED** [review]
Didn't found anything. Looks good to me

File: p2p/p2p-core/src/client/weak.rs [hunk 2]
```diff
@@ -84,29 +88,76 @@ impl<Z: NetworkZone> Service<PeerRequest> for WeakClient<Z> {
...
+///
+/// This means that if another [`WeakClient`] has a request in progress [`WeakBroadcastClient`] can
+/// still send messages and does not need to wait for the other [`WeakClient`] to finish.
+///
+/// A thing to note is that a call to [`WeakBroadcastClient::poll_ready`] will still reserve a slot
+/// in the queue, this should be kept in mind as many [`WeakBroadcastClient`]s calling [`WeakBroadcastClient::poll_ready`]
+/// without [`WeakBroadcastClient::call`] will stop other [`WeakBroadcastClient`]s & the other types
+/// of clients.
+///
+/// This type keeps it state in the [`WeakClient`] it was produced from, allowing you to do this:
```
Comment (hinto-janai) [inline p2p/p2p-core/src/client/weak.rs:116]: nit
```suggestion
/// This type is kept in state with the [`WeakClient`] it was produced from, allowing you to do this:
```

**Review by hinto-janai — APPROVED** [review]
